REM Post Upgrade Script Generated on: 2013-07-24 15:00:32 
REM Generated by Version: 12.1.0.1 Build: 006
SET ECHO OFF SERVEROUTPUT ON FORMAT WRAPPED TAB OFF LINESIZE 750;
BEGIN
  dbms_output.put_line ('Post Upgrade Fixup Script Generated on 2013-07-24 15:00:32  Version: 12.1.0.1 Build: 006');
  dbms_output.put_line ('Beginning Post-Upgrade Fixups...');
END;
/
BEGIN
dbms_preup.clear_run_flag(FALSE);
END;
/
BEGIN
-- *****************  Fixup Details ***********************************
-- Name:        OLD_TIME_ZONES_EXIST
-- Description: Check for use of older timezone data file
-- Severity:    Informational
-- Action:      ^^^ MANUAL ACTION REQUIRED ^^^
-- Fix Summary: 
--     Update the timezone using the DBMS_DST package after upgrade is complete.

dbms_preup.run_fixup_and_report('OLD_TIME_ZONES_EXIST');
END;
/
BEGIN
dbms_output.put_line ('**********************************************************************');
dbms_output.put_line ('                     [Post-Upgrade Recommendations]');
dbms_output.put_line ('**********************************************************************');
dbms_output.put_line ('');
END;
/
BEGIN
dbms_output.put_line ('                        *****************************************');
dbms_output.put_line ('                        ******** Fixed Object Statistics ********');
dbms_output.put_line ('                        *****************************************');
dbms_output.put_line ('');
dbms_output.put_line ('Please create stats on fixed objects two weeks');
dbms_output.put_line ('after the upgrade using the command:');
dbms_output.put_line ('   EXECUTE DBMS_STATS.GATHER_FIXED_OBJECTS_STATS;');
dbms_output.put_line ('');
dbms_output.put_line ('^^^ MANUAL ACTION SUGGESTED ^^^');
dbms_output.put_line ('');
END;
/
BEGIN dbms_preup.fixup_summary(FALSE); END;
/
BEGIN
dbms_output.put_line ('*************** Post Upgrade Fixup Script Complete ********************');
END;
/
REM Post Upgrade Script Closed At: 2013-07-24 15:00:48 
